export const brandName = "ArcStack"

export const uiConstants = {
  homeBadge: "Invent with Purpose",
  homeHeader: "Empower with AI",
  homeIntro1: "Get tools to take care of the innovation with AI",
  homeIntro2: "Start with a fabric tier, Upgrade on demand",
  homeIntro3: "Create a free account & get $100 credit in your wallet",
  connectionErrorMessage: "Connection Error",
  authVerificationMessage: "Verifying Credentials",
  errorMessage: "Not Found",
  toastSuccess: "Action Success",
  toastError: "Something went wrong",
  notification: "Notification",
  copiedToClipBoard: "Copied to Clipboard",
  invalidOTP: "Invalid OTP",
  authVerificationSuccess: "Credentials Verified",
  linkedinUri: "https://www.linkedin.com/in/arnhazra",
  githubRepoUri: `https://github.com/arnhazra/${brandName.toLowerCase()}`,
  confirmDescription: "This action may not be undone. Be sure before you click on continue, you can cancel if you do not want to proceed.",
  copyrightText: "Inc, All rights reserved.",
  solutionHeader: `Find solutions for putting your ideas into action. Solve your business problems with proven combinations of ${brandName} services, as well as sample architectures and documentation.`,
  openSourceHeader: `${brandName} is open source and powered by open source software.`,
  productsHeader: "Explore products for bringing your vision to life. Access all products for different needs with just a free account.",
  computeTierHeader: `Choose an ${brandName} compute tier that is right for you. Downgrade, upgrade any time. ${brandName} offers a variety of plans to meet your requirements.`,
  privacyPolicyStatement: `By using ${brandName}, you agree to our Terms of Service and Privacy Policy`,
  verifyEmailStatement: `Please verify your auth by entering the OTP we sent to your email`,
  organizationCreated: "Organization created",
  organizationSwitched: "Organization switched",
  organizationDeleted: "Organization deleted",
  apiRefreneceStatement: "You must send client_id & client_secret in headers to authenticate with your organization",
  aiSafetyStatement: `As an AI LLM ${brandName} Intelligence can make mistakes. Please be aware.`
}