name: CI-CD-UI-SERVICE
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD_UI }}
on:
  push:
    branches:
      - main

jobs:
  CI-CD-UI-SERVICE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        working-directory: apps/uiservice
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: apps/uiservice
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        working-directory: apps/uiservice
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
